### ISSUE TITLE
为什么是npm install web-storage-cache --save-dev

### ISSUE THREAD

**Issue by snowdream** [WQTeam/web-storage-cache#11]
而不是npm install web-storage-cache

**Comment by wuchangming** [comment]
@snowdream ，这个还是取决于项目。之前设想是这个只是开发依赖，一般项目都是会通过webpack之类的编译。当然了，不加这个配置项也是OK的

**Comment by snowdream** [comment]
@wuchangming 如果是通过webpack编译，还需要额外配置吗/

**Comment by wuchangming** [comment]
不需要，和一般的库一样使用即可

**Comment by snowdream** [comment]
ok
