### ISSUE TITLE
Packaging issues with 1.0.1 via NPM

### ISSUE THREAD

**Issue by biddster** [WQTeam/web-storage-cache#4]
I've been having problems with require not finding web-storage-cache 1.0.1 and I think I've pinned it down to a change made in this commit:

https://github.com/WQTeam/web-storage-cache/commit/88c4bd6f29292843b35563fc0db5586638ac1da3

Package.json was changed to this:

```
  "main": "dist/web-storage-cache.js",
```

...and I think it should actually be this (as it was in 1.0.0):

```
  "main": "src/web-storage-cache.js",
```

The path referencing dist doesn't exist as the minified version is in the dist folder.

Also, should the browser property be this?

```
"browser": "dist/web-storage-cache.min.js",
```

**Comment by wuchangming** [comment]
@biddster ,Thanks!!!

Fixed in 1.0.2

**Comment by biddster** [comment]
Confirming fixed in 1.0.2. Thank you.

**Comment by bammoo** [comment]
@wuchangming The package install instruction should be added to README.md.

**Comment by wuchangming** [comment]
@bammoo 
Good suggest, it has been added in `README.md` and  `README_en.md`
