### ISSUE TITLE
超时截止日期的api貌似写错了？

### ISSUE THREAD

**Issue by Robot-L** [WQTeam/web-storage-cache#5]
api介绍是这样的：
```
// 超时截止日期 2015 5 18
cache.set('username', 'xx', {exp : new Date('2015 5 `18')});
```

但出现报错信息：
`web-storage-cache.js:205 Uncaught Error: `expires` parameter cannot be converted to a valid Date instance
`

查看源码没有参数为Date类型的处理语句，应该是直接传字符串就行了
`cache.set('username', 'xx', {exp : '2015 5 `18'});`

**Comment by wuchangming** [comment]
你的多了个点（`）。
```
cache.set('username', 'xx', {exp : new Date('2015 5 `18')});  ❌
cache.set('username', 'xx', {exp : new Date('2015 5 18')});    ✅
```
Date是浏览器的内部类型

<img width="494" alt="screen shot 2016-10-20 at 9 56 45 am" src="https://cloud.githubusercontent.com/assets/5039340/19543737/34b92918-96ac-11e6-8507-6db2f76c7787.png">

**Comment by Robot-L** [comment]
是我看错代码了，上面的代码是复制到评论框的时候不小心按的。。。
