### ISSUE TITLE
Constructor的问题

### ISSUE THREAD

**Issue by Robot-L** [WQTeam/web-storage-cache#6]
楼主问一下，
`var defaults = {
        storage: 'localStorage',
        exp: Infinity  //An expiration time, in seconds. default never .
    };`
**这里的构造函数中的exp在后面代码中并没有使用过啊，在set方法中如果不设exp的话用得就是_maxExpireDate的时间，我用new  WebStorageCache({exp:100}).set("x","y");用开发者工具查看的数据中
{"c":1476957713537,"e":7955078400000,"v":"\"hello\""}过期时间e依旧是_maxExpireDate设置的时间的毫秒数

**Comment by wuchangming** [comment]
@Robot-L ,**非常感谢！**
这里确实是有bug。
最新版本1.0.3已修复了该问题。
